services:
  database:
    build: ./database
    container_name: database
    restart: always
    ports:
      - "3307:3306"
    networks:
      - "spring_net"
  
  backend:
    build: ./backend/backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - spring_net
    depends_on:
      - database
    
networks:
  spring_net: